feature/SEO-blogdetail-page
blockfint/blockfint-landing-2020 pull request #92
Opened 2021-05-28 09:08 UTC by thanakrit07

add SEO to every page

2021-05-28 10:34 UTC, jakapatb commented
หน้าแรก ถูกละ
![Screen Shot 2564-05-28 at 17 33 14](https://user-images.githubusercontent.com/38038597/119971137-cabb9980-bfda-11eb-80e1-9e260f47594c.png)

หน้า blog detail ต้องขึ้นรูป head เหมือนของ gideon blog
http://debug.iframely.com/?uri=https%3A%2F%2Fblockfint-land-git-feature-seo-blogdetail-page-bl-901b85.vercel.app%2Fblog%2Ffirstblog
![Screen Shot 2564-05-28 at 17 33 40](https://user-images.githubusercontent.com/38038597/119971184-d8711f00-bfda-11eb-9dfe-3615fa152943.png)

2021-05-28 10:34 UTC, jakapatb requested changes
หน้าแรก ถูกละ
![Screen Shot 2564-05-28 at 17 33 14](https://user-images.githubusercontent.com/38038597/119971137-cabb9980-bfda-11eb-80e1-9e260f47594c.png)

หน้า blog detail ต้องขึ้นรูป head เหมือนของ gideon blog
http://debug.iframely.com/?uri=https%3A%2F%2Fblockfint-land-git-feature-seo-blogdetail-page-bl-901b85.vercel.app%2Fblog%2Ffirstblog
![Screen Shot 2564-05-28 at 17 33 40](https://user-images.githubusercontent.com/38038597/119971184-d8711f00-bfda-11eb-9dfe-3615fa152943.png)

2021-05-31 04:42 UTC, thanakrit07 commented
ตอนนี้ title กับ description มาละ แต่ว่าตัว og:image ของตัว post มันไม่มีรูปก็จะเป็นกล่อง blockfintอยู่

2021-05-31 06:06 UTC, jakapatb approved these changes

2021-05-31 06:06 UTC, merged